alias ls='ls -F'
alias la='ls -la'
alias ll='ls -lh'
alias i3conf='micro ~/.config/i3/config'
alias stconf='micro ~/.config/py3status/config'
alias duconf='micro ~/.config/dunst/dunstrc'
alias piconf='micro ~/.config/picom/picom.conf'
alias kiconf='micro ~/.config/kitty/kitty.conf'
alias transmission="transmission-daemon && tremc"
