alias ..='cd ..'
alias ...='cd ...'
alias ls='exa'
alias la='exa -la'
alias ll='exa -lh'
alias cat='bat'
alias print='figlet'
alias count='find . -type f | wc -l'
alias clock='tty-clock -c'
alias term='xfce4-terminal'
alias pipes='pipes.sh'
alias intop='sudo intel_gpu_top'
alias lockscreen='i3lock -c 00000000 -B 1 -k --indicator --insidever-color=5ac8c865 --insidewrong-color=f0898965 --inside-color=00000075 --ringver-color=5ac8c8ff --ringwrong-color=f06c6c65 --ring-width=1.0 --ring-color=ffffff --line-uses-inside --keyhl-color=5ac8c8ff --bshl-color=5ac8c8ff --separator-color=00000065 --verif-color=ffffffff --wrong-color=ffffffff --time-color=ffffffff --date-color=ffffffff --greeter-color=ffffffff --time-str="%H:%M" --date-str="%A" --time-font="Noto Sans Thin:style=Thin" --date-font="Noto Sans Thin:style=Thin" --layout-font="Noto Sans Thin:style=Thin" --verif-font="Noto Sans Thin:style=Thin" --wrong-font="Noto Sans Thin:style=Thin" --greeter-font="Noto Sans Thin:style=Thin" --time-size=64 --date-size=20 --radius 110'
alias awconf='micro ~/.config/awesome/rc.lua'
alias piconf='micro ~/.config/picom/picom.conf'
alias kiconf='micro ~/.config/kitty/kitty.conf'
alias upsearch='sudo updatedb -U "$HOME" -e "$HOME/.config" -e "$HOME/.local" -e "$HOME/.cache"'
alias transmission="transmission-daemon && tremc"
